name: Scheduled Node.js CI

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run a script
        run: node main.js
      # 下面是新添加的邮件发送步骤
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          # Server settings
          server_address: smtp.gmail.com
          server_port: 465
          # Authentication
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # Email settings 
          subject: Scheduled CI Execution Result
          # Assuming 'output' is the content you want to send
          body: file://path/to/output.txt  
          to: hsm623@gmail.com
          from: CI System <no-reply@example.com>
