name: Scheduled Node.js CI

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build_and_notify:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2 # 或 @v3，取决于您使用的版本

      - name: Setup Node
        uses: actions/setup-node@v2 # 或 @v3，取决于您使用的版本
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm install

      - name: Run a script and save output
        run: node main.js > output.txt

      - name: Send mail with output file
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: Scheduled CI Execution Result
          body: The output of the CI execution is attached.
          to: hsm623@gmail.com
          from: CI System <no-reply@example.com>
          attachments: output.txt
